version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - .env
  api:
    stdin_open: true
    tty: true
    build: ./ati2-lab-back
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  web:
    stdin_open: true
    tty: true
    build: ./ati2-lab-front
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - api

