version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ati-lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ati-lab-1337*
  api:
    stdin_open: true
    tty: true
    build: ./ati2-lab-back
    environment:
      - DJANGO_SETTINGS_MODULE=back.settings.dev
      - SECRET_KEY=<SECRET_KEY>
      - ALLOWED_HOSTS=*
      - DATABASE_NAME=ati2_lab_back
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=localhost
      - DATABASE_PORT=
      - EMAIL_HOST=<MAIL_HOST>
      - EMAIL_HOST_USER=<EMAIL>
      - EMAIL_HOST_PASSWORD=<PASSWORD>
      - PHONENUMBER_DEFAULT_REGION=VE
    ports:
      - 8000:8000
    depends_on:
      - db
  web:
    stdin_open: true
    tty: true
    build: ./ati2-lab-front
    environment:
      - API_BASE_URL=http://web
    ports:
      - 3000:3000
    depends_on:
      - api


