version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  api:
    stdin_open: true
    tty: true
    build: ./ati2-lab-back
    volumes:
      - .env:/code/back/settings/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  web:
    stdin_open: true
    tty: true
    build: ./ati2-lab-front
    volumes:
      - .env:/code/.env.local
    ports:
      - 3000:3000
    depends_on:
      - api

